<?php
declare(strict_types=1);
namespace Console\Helpers;

/**
 * A collection of React.js view, component, and util stubs.
 */
class ReactStubs {
    /**
     * Sub for auth/Login.jsx page component.
     *
     * @return string The contents of the auth/Login.jsx page component.
     */
    public static function authLogin(): string {
        return <<<'JSX'
import React from "react";
import route from "@chappy/utils/route";
import Forms, { CheckBoxLeftLabel } from "@chappy/components/Forms";

/**
 * @property {object} errors The errors object.
 * @property {object} login The login model object
 * @param {InputProps} param0 
 * @returns {JSX.Element} The contents 
 */
function Login({errors, login, rememberMeChecked}) {
    return(
        <div className="row align-items-center justify-content-center">
            <div className="col-md-6 bg-light p-3">
                <h1 className="text-center">Login</h1>
                <form className="form" action={route('auth.login')} method="post">
                    <Forms.CSRFInput />
                    <Forms.DisplayErrors errors={errors}/>
                    <Forms.Input 
                        type="text"
                        label="Username"
                        name="username"
                        value={login.username}
                        inputAttrs={{className: 'form-control'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Password"
                        name="password"
                        value={login.password}
                        inputAttrs={{className: 'form-control'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />

                    <CheckBoxLeftLabel
                        label="Remember Me"
                        name="remember_me"
                        value="on"
                        checked={rememberMeChecked}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <div className="d-flex justify-content-end">
                        <div className="flex-grow-1 text-body">
                            Don't have an account? <a href={route('auth.register')}>Sign Up</a>
                        </div>
                        <Forms.SubmitTag label={"login"} inputAttrs={{className: 'btn btn-primary'}}/>
                    </div>
                </form>
            </div>
        </div>
    )
}

export default Login;
JSX;
    }

    /**
     * Stub for auth/Register.jsx page component.
     *
     * @return string The contents of the auth/Register.jsx page component.
     */
    public static function authRegister(): string {
        return <<<'JSX'
import React from "react";
import Forms from "@chappy/components/Forms";
import {PasswordComplexityRequirements} from '@chappy/components/PasswordComplexityRequirements';

/**
 * Generates the register view component
 * @property {object} user The users model object.
 * @property {object} errors The errors generated by the users model.
 * @param {InputProps} param0 
 * @returns {JSX.Element} The register view component.
 */
function Register({user, errors}) {
    return (
        <div className="row align-items-center justify-content-center">
            <div className="col-md-6 bg-light p-3">
                <h3 className="text-center">Register Here!</h3>
                <hr />
                <form action="" className="form" method="post" encType="multipart/form-data">
                    <Forms.CSRFInput />
                    <Forms.DisplayErrors errors={errors}/>
                    <Forms.Input 
                        type="text"
                        label="User name"
                        name="username"
                        value={user.username}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Input 
                        type="text"
                        label="First Name"
                        name="fname"
                        value={user.fname}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Input 
                        type="text"
                        label="Last Name"
                        name="lname"
                        value={user.lname}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Email 
                        label="Email"
                        name="email"
                        value={user.email}
                        inputAttrs={{className: 'form-control input-sm', placeholder: 'joe@example.com'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.RichText
                        label="Description"
                        name="description"
                        value={user.description || ""}
                        inputAttrs={{ placeholder: 'Describe yourself here...' }}
                        divAttrs={{ className: 'form-group mb-3' }}
                    />
                    <Forms.Input 
                        type="file"
                        label="Upload Profile Image (Optional"
                        name="profileImage"
                        value=""
                        inputAttrs={{className: 'form-control', accept: 'image/gif image/jpeg image/png'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <PasswordComplexityRequirements />
                    <Forms.Input 
                        type="password"
                        label="Password"
                        name="password"
                        value={user.password}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Confirm Password"
                        name="confirm"
                        value={user.confirm}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.SubmitBlock
                        label="Register"
                        inputAttrs={{className: 'btn btn-large btn-primary'}}
                        divAttrs={{className: 'text-end'}}
                    />
                </form>
            </div>
        </div>
    );
}

export default Register;
JSX;
    }

    /**
     * Generates reset password view for auth controller.
     *
     * @return string The contents for the JSX file.
     */
    public static function authResetPassword(): string {
        return <<<'JSX'
import React from "react";
import Forms from "@chappy/components/Forms";
import {PasswordComplexityRequirements} from '@chappy/components/PasswordComplexityRequirements';
import documentTitle from "@chappy/utils/documentTitle";

/**
 * Render component for password reset view.
 * 
 * @property {object} user The user whose password to be reset.
 * @property {array} errors The errors generated by the users model.
 * @param {InputProps} param0 
 * @returns {JSX.Element} Component for password reset view.
 */
function ResetPassword({ user, errors }) {
    documentTitle("Reset Password");
    return (
        <div className="row align-items-center justify-content-center">
            <div className="col-md-6 bg-light p-3">
                <h3 className="text-center">Reset Password</h3>
                <PasswordComplexityRequirements />
                <form className="form" action="" method="post">
                    <Forms.CSRFInput />
                    <Forms.DisplayErrors errors={errors} />
                    <Forms.Input 
                        type="password"
                        label="Password"
                        name="password"
                        value={user.password}
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-3"}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Confirm Password"
                        name="confirm"
                        value={user.confirm}
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-3"}}
                    />
                    <Forms.SubmitTag label="Set Password" inputAttrs={{className: "btn btn-primary"}} />
                </form>
            </div>
        </div>
    );
}        
export default ResetPassword;
JSX;
    }

    /**
     * Generates a component with default export.
     *
     * @param string $componentName The name of the component.
     * @return string The contents of the component.
     */
    public static function defaultComponentTemplate(string $componentName): string {
        return <<<JSX
import React from "react";
function {$componentName}() {

    return (
        <>
        
        </>
    );
}        
export default {$componentName};
JSX;
    }

    /**
     * Stub for restoring required error/NotFound.jsx page component if 
     * accidentally deleted.
     *
     * @return string Contents of the error/NotFound.jsx page component.
     */
    public static function errorNotFound(): string {
        return <<<'JSX'
import React from "react";

/**
 * Renders error page with "The view was not found message".
 * @returns {JSX.Element} H1 element with "The view was not found" message.
 */
export default function NotFound() {
    return <h1 className="text-center">The view was not found</h1>
}
JSX;
    }

    /**
     * Stub for home/Index.jsx page component.
     *
     * @return string The contents of the home/Index.jsx page component.
     */
    public static function homeIndex(): string {
        return <<<'JSX'
import React from "react";
import asset from '@chappy/utils/asset'
/**
 * The home page.
 * @property {object} user The currently logged in user.
 * @property {string} version The current version of the Chappy.php framework.
 * @param {InputProps} param0 
 * @returns {JSX.Element} The contents of Index view.
 */
export default function Index({ user, version }) {
    const name = user.fname ?? 'Guest';
    return (
        <div className="container">
            <div className="text-center">
                <h1 className="display-4">Hello, {name} 👋</h1>
                <h1 className="display-4">Welcome to</h1>
                <div className="col-12 mx-auto text-center">
                    <img className="w-50" src={asset("public/logo.png", true)} alt="Framework Logo" />
                </div>
                <p className="lead my-3">
                    A lightweight and modern PHP framework built for simplicity, speed, and the power of React.js.
                </p>
                <p className="lead my-3">This view is powered by React + Vite.</p>

                <div className="d-flex justify-content-center mt-4 flex-wrap gap-3">
                    <a className="btn btn-primary" href="https://chapmancbvcu.github.io/chappy-php-starter/">📘 View Documentation</a>
                </div>
            </div>

            <hr className="my-5"/>

            <div className="row text-center g-4">
                <div className="col-md-4">
                    <h4>🔧 MVC Architecture</h4>
                    <p>Familiar routing and controller setup with simple view rendering.</p>
                </div>
                <div className="col-md-4">
                    <h4>🛡️ Custom Forms With Validation</h4>
                    <p>A FormHelper class with support for many commonly used elements and built-in server-side form validation with error message support.</p>
                </div>
                <div className="col-md-4">
                    <h4>⚙️ Project Generator</h4>
                    <p>Generate project skeletons and database migrations using console commands.</p>
                </div>
            </div>

            <div className="row text-center g-4 mt-4">
                <div className="col-md-4">
                    <h4>🧩 Composer and npm Support</h4>
                    <p>Manage your dependencies using Composer and npm.</p>
                </div>
                <div className="col-md-4">
                    <h4>📁 User Management</h4>
                    <p>Includes ACL support and authentication out of the box.</p>
                </div>
                <div className="col-md-4">
                    <h4>📄 Simple Documentation</h4>
                    <p>Markdown and API documentation included and easy to customize.</p>
                </div>
            </div>
            <p className="text-center text-muted mt-5">
                To customize this page, edit <code>resources/js/pages/home/Index.jsx</code> and <code>app/Controllers/HomeController.php</code>.
            </p>
            <p className="text-center text-muted mb-5">
                Chappy.php Framework v{version}
            </p>
        </div>
    );
}
JSX;
    }

    /**
     * Returns contents for a new hook file.
     *
     * @param string $hookName The name of the hook.
     * @return string The contents of the new hook file.
     */
    public static function hookTemplate($hookName): string {
        return <<<JS
const use{$hookName} = () => {

    return {  }
}

export default use{$hookName};
JS;
    }

    /**
     * Generates a named export component.
     *
     * @param string $componentName The name of the component.
     * @return string The contents of the component.
     */
    public static function namedComponentTemplate(string $componentName): string {
        return <<<JSX
import React from "react";
export const {$componentName} = () => {

    return (
        <>
        
        </>
    );
}
JSX;
    }
    /**
     * Stub for ProfileImageSorter.jsx component.
     *
     * @return string The contents of ProfileImageSorter.jsx file.
     */
    public static function profileImageSorter(): string {
        return <<<'JSX'
import React, { useEffect, useRef, useState } from 'react';
import $ from 'jquery';
import 'jquery-ui-dist/jquery-ui.css';
import { getCsrf } from '@chappy/utils/csrf';
import '@css/profileImage.css';
import asset from '@chappy/utils/asset';

/**
 * A single profile image row used by the sorter.
 * @typedef {Object} ProfileImage
 * @property {number|string} id     - Unique image identifier.
 * @property {string}        url    - Public URL for the image.
 * @property {number}       [sort]  - Optional sort index (0 = current profile image).
 */

/**
 * Props for {@link ProfileImageSorter}.
 * @typedef {Object} ProfileImageSorterProps
 * @property {ProfileImage[]} [initialImages=[]]
 *   Initial list of images to display and sort.
 * @property {string} [deleteEndpoint='/profile/deleteImage']
 *   Endpoint that deletes an image. Expects `POST image_id, csrf_token`
 *   and returns JSON `{ success: boolean, model_id?: string|number }`.
 */

/**
 * Drag-to-reorder gallery with a hidden `<input name="images_sorted">` that
 * mirrors the order in a PHP-friendly format (e.g. `["image_1","image_9",...]`).
 *
 * - Uses jQuery UI `sortable` (horizontal).
 * - On delete, POSTs `image_id` + CSRF, removes from UI on success, and refreshes order.
 *
 * @param {ProfileImageSorterProps} props
 * @returns {JSX.Element}
 */
export default function ProfileImageSorter({
    initialImages = [],
    deleteEndpoint = '/profile/deleteImage',
}) {
    /** 
     * The working list of images shown in the UI. 
     */
    const [images, setImages] = useState(initialImages);

    /** 
     * Root element that receives the jQuery UI `sortable()` binding. 
     */
    const listRef = useRef(null);

    /** 
     * Hidden input that carries the serialized order for the PHP controller. 
     */
    const sortedRef = useRef(null);

    /**
     * Initialize / re-initialize sortable whenever the number of items changes.
     * Cleans up the jQuery UI instance on unmount.
     */
    useEffect(() => {
        const el = listRef.current;
        if (!el) return;

        window.$ = window.jQuery = $;
        let destroyed = false;

        (async () => {
            await import('jquery-ui-dist/jquery-ui');

            if (destroyed) return;

            const $el = $(el);
            if ($el.data('ui-sortable')) {
                $el.sortable('refresh');
            } else {
                $el.sortable({
                axis: 'x',
                placeholder: 'sortable-placeholder',
                update: updateHidden,
                });
            }

            // Seed initial hidden value
            updateHidden();
        })();

        return () => {
            destroyed = true;
            try { $(el).sortable('destroy'); } catch {}
        };
    }, [images.length]);

    /**
     * Compute the current DOM order and write it into the hidden field as JSON.
     * The IDs follow the original PHP pattern: container IDs like "image_<id>".
     * @returns {void}
     */
    function updateHidden() {
        const arr = $(listRef.current).sortable('toArray');
        if (sortedRef.current) sortedRef.current.value = JSON.stringify(arr);
    }

    /**
     * Delete an image from the server and update local state if successful.
     *
     * @param {number|string} id - The image ID to remove.
     * @returns {Promise<void>}
     */
    async function handleDelete(id) {
        if (!confirm('Are you sure? This cannot be undone!')) return;
        const fd = new FormData();
        fd.append('image_id', id);
        fd.append('csrf_token', getCsrf());

        const res = await fetch(deleteEndpoint, { method: 'POST', body: fd, credentials: 'same-origin' });
        let data = null; 
        try { 
            data = await res.json(); 
        } catch {}

        if (data?.success) {
            // Remove from UI, `useEffect` will refresh hidden order
            setImages(prev => prev.filter(img => img.id !== id));
            window.alert?.('Image Deleted.');
        }
    }


    return (
        <>
            <input ref={sortedRef} type="hidden" name="images_sorted" />
            <div id="sortableImages" className="row align-items-center justify-content-start p-2" ref={listRef}>
                {images.map(img => (
                <div key={img.id} className="col flex-grow-0" id={`image_${img.id}`}>
                    <button type="button" className="btn btn-danger btn-sm mb-2" onClick={() => handleDelete(img.id)}>
                    <i className="fa fa-times" />
                    </button>
                    <div className={`edit-image-wrapper ${img.sort === 0 ? 'current-profile-img' : ''}`} data-id={img.id}>
                    <img src={asset(img.url)} alt="" />
                    </div>
                </div>
                ))}
            </div>
        </>
    );
}
JSX;
    }

    /**
     * Stub for profile/Edit.jsx page component.
     *
     * @return string The contents of the profile/Edit.jsx page component.
     */
    public static function profileEdit(): string {
        return <<<'JSX'
import React from "react";
import Forms from "@chappy/components/Forms";
import route from "@chappy/utils/route";
import ProfileImageSorter from '@/components/ProfileImageSorter';
import documentTitle from '@chappy/utils/documentTitle';

/**
 * Generates the edit profile component
 * @property {object} user The users model object.
 * @property {object} errors The errors generated by the users model.
 * @property {array} profileImage Array that contains object for currently 
 * selected profile image.
 * @param {InputProps} param0 
 * @returns {JSX.Element} The edit profile view component.
 */
function Edit({user, errors, profileImages}) {
    documentTitle(`Edit Details for ${user.username}`);

    return (
        <div className="row align-items-center justify-content-center mb-5">
            <div className="col-md-6 bg-light p-3">
                <h1 className="text-center">Edit Details for {user.username}</h1>
                <hr />
                <form className="form" action="" method="post" encType="multipart/form-data">
                    <Forms.CSRFInput />
                    <Forms.DisplayErrors errors={errors}/>
                    <Forms.Input 
                        type="text"
                        label="First Name"
                        name="fname"
                        value={user.fname}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Input 
                        type="text"
                        label="Last Name"
                        name="lname"
                        value={user.lname}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Email 
                        label="Email"
                        name="email"
                        value={user.email}
                        inputAttrs={{className: 'form-control input-sm', placeholder: 'joe@example.com'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.RichText
                        label="Description"
                        name="description"
                        value={user.description}
                        inputAttrs={{ placeholder: 'Describe yourself here...' }}
                        divAttrs={{ className: 'form-group mb-3' }}
                    />

                    <Forms.Input 
                        type="file"
                        label="Upload Profile Image (Optional)"
                        name="profileImage"
                        value=""
                        inputAttrs={{className: 'form-control', accept: 'image/gif image/jpeg image/png'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />

                    <ProfileImageSorter initialImages={profileImages} deleteEndpoint="/profile/deleteImage" />
                    <div className="col-md-12 text-end">
                        <a href={route('profile')} className="btn btn-default">Cancel</a>
                        <Forms.SubmitTag label={"Submit"} inputAttrs={{className: 'btn btn-primary'}}/>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default Edit;
JSX;
    }

    /**
     * Stub for profile/Index.jsx page component.
     *
     * @return string The contents of the profile/Index.jsx component.
     */
    public static function profileIndex(): string {
        return <<<'JSX'
import React from "react";
import SafeHtml from '@chappy/components/SafeHtml.jsx';
import asset from '@chappy/utils/asset'
import route from "@chappy/utils/route";
import documentTitle from "@chappy/utils/documentTitle";

/**
 * Renders index view for profile controller.
 * @param {string} param0 Props for user and current profile image URL.
 * @returns {JSX.Element} The component for the profile index view.
 */
function Index({ user, profileImage }) {
    documentTitle(`Profile Details for ${user.username}`);

    return (
        <>
            <h1 className="text-center">Profile Details for {user.username}</h1>
            <div className="col align-items-center justify-content-center mx-auto my-3 w-50">
                {profileImage && (
                    <img src={asset(profileImage.url)}
                        className="img-thumbnail mx-auto my-5 d-block w-50 rounded border border-primary shadow-lg"
                        loading="lazy"
                    />
                )}

                <table className="table table-striped  table-bordered table-hover bg-light my-5">
                    <tbody>
                        <tr>
                            <th className="text-center">First Name</th>
                            <td className="text-center">{user.fname}</td>
                        </tr>
                        <tr>
                            <th className="text-center">Last Name</th>
                            <td className="text-center">{user.lname}</td>
                        </tr>
                        <tr>
                            <th className="text-center">E-mail</th>
                            <td className="text-center">{user.email}</td>
                        </tr>
                        <tr>
                            <th className="text-center">ACL</th>
                            <td className="text-center">{user.acl}</td>
                        </tr>
                        <tr>
                            <th className="text-center" colSpan={2}>
                                {user.description ? 'Description' : 'No description'}
                            </th>
                            
                        </tr>
                        {user.description && (
                            <tr>
                                <td id="description" className="p-4" colSpan={2}>
                                    <SafeHtml html={user.description} decode className="prose"/>
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
                <div className="mb-5 d-flex justify-content-around">
                    <a href={route('profile.edit')} className="btn btn-info btn-sm mx-2 mb-3">
                        <i className="fa fa-edit"></i> Edit User Profile
                    </a>
                    <a href={route('profile.updatePassword')} className="btn btn-danger btn-sm mx-2 mb-3">
                        <i className="fa fa-key"></i> Update Password
                    </a>
                </div>
            </div>
        </>
    );
}

export default Index;
JSX;
    }

    /**
     * Stub for profile/UpdatePassword.jsx page component
     *
     * @return string The contents of the profile/UpdatePassword.jsx component.
     */
    public static function profileUpdatePassword(): string {
        return <<<'JSX'
import React from "react";
import Forms from "@chappy/components/Forms";
import {PasswordComplexityRequirements} from '@chappy/components/PasswordComplexityRequirements';
import route from "@chappy/utils/route";
import documentTitle from "@chappy/utils/documentTitle";

/**
 * Render component for password update view.
 * 
 * @property {object} user The user whose password is to be reset.
 * @property {array} errors The errors generated by the users model.
 * @param {InputProps} param0 
 * @returns {JSX.Element} Component for password update view.
 */
function UpdatePassword({user, errors}) {
    documentTitle(`Change Password for ${user.username}`);

    return (
        <div className="row align-items-center justify-content-center">
            <div className="col-md-6 bg-light p-3">
                <h1 className="text-center">Change Password for {user.username}</h1>
                <hr />
                <PasswordComplexityRequirements />
                <form className="form" action="" method="post">
                    <Forms.CSRFInput />
                    <Forms.DisplayErrors errors={errors}/>
                    <Forms.Input 
                        type="password"
                        label="Current Password"
                        name="current_password"
                        value=""
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-3"}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Password"
                        name="password"
                        value=""
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-3"}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Confirm Password"
                        name="confirm"
                        value=""
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-4"}}
                    />
                    <div className="col-md-12 text-end">
                        <a href={route("profile")} className="btn btn-default">Cancel</a>
                        <Forms.SubmitTag label="Update" inputAttrs={{className: "btn btn-primary"}} />
                    </div>
                </form>
            </div>
        </div>
    );
}        
export default UpdatePassword;
JSX;
    }
}